### ISSUE TITLE
Add Collaborative Community Review text/explainer to ccr.meshresearch.dev.

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#1055] opened 2022-04-29 19:48 UTC
### Problem/Why
The CCR application's documentation site's explanation of rationale/importance/methodology behind the app is lacking.

### Solution/How
Create broadly applicable documentation for the documentation site based on the [new PPJ site](http://ppj.mesh.msu.domains/about-community-collaborative-review/) and the literature around peer review, open peer review, and PPJ.

### To Do / Acceptance Criteria

- [x] SEV drafts text 
- [x] SEV sends text to SB for review
- [ ] Update documentation site with new copy

### Review Checklist

- [ ] New text is understandable and error free.

### Accessibility Checklist

- [ ]

**Comment by sattler9** [comment] 2022-04-29 19:59
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1055?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality

**Comment by gmeben** [comment] 2022-05-25 17:15
1. What content specifically from [the linked page](https://publicphilosophyjournal.org/about-community-collaborative-review/) must be ported? The whole page? Selected portions? 

2. Where specifically is the intended destination for the ported documentation? The [homepage](http://docs.ccr.lndo.site)? The [Guide](http://docs.ccr.lndo.site/guide/) page?

**Comment by wreality** [comment] 2022-05-25 18:14
The content needs to be generalized to refer to the CCR process rather than specific to PPJ. 

The guide page is fine.

**Comment by gmeben** [comment] 2022-05-25 19:28
We've decided as a team in today's team time that this work is dependent on copyediting to be performed by PPJ and so we will be moving this issue back to the Product Backlog until that copyediting has been completed.

**Comment by gmeben** [comment] 2022-08-01 16:22
I confirmed in today's meeting with PPJ that the copyediting on this page is in a finalized state, but that there is a desire to give it one more review before its approval to be ported into the docs site.

**Closed** 2022-08-29 20:09 UTC
Labels: 📖 documentation, 🖥️ frontend
